### PR TITLE
Initial code commit w/ README.

### PR DESCRIPTION
**Pull request by CoreyShupe**
Added simple wrapper around starting the bot
Added example PingBot

### CODE REVIEW

**Comment by ianagbip1oti** [comment]
Should there be a call to `SmallD#close` in here somewhere?

**Comment by CoreyShupe** [comment]
> Should there be a call to `SmallD#close` in here somewhere?

I'm not quite sure where you'd want it, I'm just following https://github.com/princesslana/smalld/blob/master/src/main/java/com/github/princesslana/smalld/examples/PingBot.java for the basic initial commit. So it works. It can be closed from within `startBot` I assume since `this` within the `startBot` block references the SmallD instance.

EDIT: I see what you mean, fixed in the next commit.

**Comment by ianagbip1oti** [comment]
If I used `startBotConnect`, it would immediately return and close the bot?

**Comment by CoreyShupe** [comment]
> If I used `startBotConnect`, it would immediately return and close the bot?

Ah you're right, it would, seems to be an issue, I may only provide run in this context, or just provide an open where they can connect and await on their own. I don't think there's a way to run without a after-run consumer.

**Comment by ianagbip1oti** [comment]
Just doing run would be good for a start.

conncet/await would just be for anyone that wanted to control the lifecycle themselves for some reason

**Comment by CoreyShupe** [comment]
> Just doing run would be good for a start.
> 
> conncet/await would just be for anyone that wanted to control the lifecycle themselves for some reason

Seems fair, will commit

**Review by ianagbip1oti — APPROVED** [review]

**Pull request merged**
